todo/todo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

todo/todoapp/urls.py
from . import views
from django.urls import path

app_name = 'todoapp'

urlpatterns = [
    path('view/',views.Tasklistview.as_view(), name='view'),
    path('cddetail/<int:pk>/', views.Taskdetailview.as_view(), name='detailtask'),
    path('cdupdate/<int:pk>/', views.Taskupdateview.as_view(), name='update'),
    path('cddelete/<int:pk>/', views.Taskdeleteview.as_view(), name='delete'),
    path('', views.index, name="index"),
    path('delete/<int:id>/', views.deletelist, name="deletelist"),
    path('update/<int:id>/', views.updatelist, name="updatelist"),
]

todo/doapp/models.py
from django.db import models

# Create your models here.

todo/todoapp/models.py
from django.db import models


# Create your models here.

class Task(models.Model):
    name = models.CharField(max_length=250)
    priority = models.IntegerField()
    date = models.DateField()

    def __str__(self):
        return  self.name

todo/todoapp/forms.py
from .models import Task
from django import forms


class Todoform(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'priority', 'date']

todo/doapp/views.py
from django.shortcuts import render

# Create your views here.

todo/todoapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from .forms import Todoform
from .models import Task
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView


class Tasklistview(ListView):
    model = Task
    template_name = 'index1.html'
    context_object_name = 'task'


class Taskdetailview(DetailView):
    model = Task
    template_name = 'view.html'
    context_object_name = 'task'


class Taskupdateview(UpdateView):
    model = Task
    template_name = 'update.html'
    context_object_name = 'task'
    fields = ['name', 'priority', 'date']

    def get_success_url(self):
        return reverse_lazy('todoapp:detailtask', kwargs={'pk': self.object.id})


class Taskdeleteview(DeleteView):
    model = Task
    template_name = 'detail.html'
    success_url = reverse_lazy('todoapp:view')


# Create your views here.

def index(request):
    task1 = Task.objects.all()
    if request.method == "POST":
        name = request.POST.get('name')
        priority = request.POST.get('priority')
        date = request.POST.get('date')
        task = Task(name=name, priority=priority, date=date)
        task.save()
    return render(request, "index.html", {'task': task1})


def deletelist(request, id):
    if request.method == "POST":
        task = Task.objects.get(id=id)
        task.delete()
        return redirect('/')
    return render(request, "detail.html")


def updatelist(request, id):
    task = Task.objects.get(id=id)
    form = Todoform(request.POST or None, instance=task)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, "edit.html", {'form': form, 'task': task})

todo/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="{% static 'style.css' %}" rel="stylesheet">
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1>Todolist with views</h1>
                </div>
            </div>
        </div>
    </div>
</div>
{% block content %}


{% endblock %}
</body>
</html>

todo/templates/base1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="{% static 'style.css' %}" rel="stylesheet">
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1>Todolist with class</h1>
                </div>
            </div>
        </div>
    </div>
</div>
{% block content %}


{% endblock %}
</body>
</html>

todo/templates/detail.html
{% extends 'base1.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Are you sure this task is done?</p>
        <input type="submit" value="confirm">
    </form>
{% endblock %}

todo/templates/edit.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="post" class="p-3 shadow">
                {% csrf_token %}
                <div class="form-group">
                   {{ form.as_p }}<br>
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-success" >
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

todo/templates/index.html
{% extends 'base.html' %}

{% block content %}


<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="post" class="p-3 shadow">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" name="name" class="form-control"  placeholder="Task Name"><br>
                </div>
                <div class="form-group">
                    <input type="text" name="priority" class="form-control"  placeholder="Priority"><br>
                </div>
                <div class="form-group">
                    <input type="date" name="date" class="form-control"  placeholder="Date"><br>
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-success" >
                </div>
            </form>
        </div>
        <div class="col-md-6">
            <h4>Task to be Completed</h4>
            {% for i in task %}
                <div class="card shadow">
                    <div class="card-body">
                        <h5 class="card-title">{{ i.name }}</h5>
                        <p><b>{{ i.priority }}</b></p>
                        <p><b>{{ i.date }}</b></p>
                        <a class="btn btn-danger" href="{% url 'todoapp:deletelist' i.id %}">Delete</a>
                        <a class="btn btn-success" href="{% url 'todoapp:updatelist' i.id %}">Update</a>
                    </div>
                </div><br>
            {% endfor %}
        </div>
    </div>
</div>



{% endblock %}

todo/templates/index1.html
{% extends 'base1.html' %}

{% block content %}


<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="post" class="p-3 shadow">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" name="name" class="form-control"  placeholder="Task Name"><br>
                </div>
                <div class="form-group">
                    <input type="text" name="priority" class="form-control"  placeholder="Priority"><br>
                </div>
                <div class="form-group">
                    <input type="date" name="date" class="form-control"  placeholder="Date"><br>
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-success" >
                </div>
            </form>
        </div>
        <div class="col-md-6">
            <h4>Task to be Completed</h4>
            {% for i in task %}
                <div class="card shadow">
                    <div class="card-body">
                        <h5 class="card-title">{{ i.name }}</h5>
                        <p><b>{{ i.priority }}</b></p>
                        <p><b>{{ i.date }}</b></p>
                        <a class="btn btn-danger" href="{% url 'todoapp:deletelist' i.id %}">Delete</a>
                        <a class="btn btn-success" href="{% url 'todoapp:updatelist' i.id %}">Update</a>
                    </div>
                </div><br>
            {% endfor %}
        </div>
    </div>
</div>



{% endblock %}

todo/templates/update.html
{% extends 'base1.html'%}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="post" class="p-3 shadow">
                {% csrf_token %}
                <div class="form-group">
                   {{ form.as_p }}<br>
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-success" >
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

todo/templates/view.html
{% extends 'base1.html' %}

{% block content %}

    <div class="card shadow">
        <div class="card-body">
            <h5 class="card-title">{{ task.name }}</h5>
            <p><b>{{ task.priority }}</b></p>
            <p><b>{{ task.date }}</b></p>
            <a class="btn btn-danger" href="{% url 'todoapp:deletelist' task.id %}">Delete</a>
            <a class="btn btn-success" href="{% url 'todoapp:updatelist' task.id %}">Update</a>
        </div>
    </div>

{% endblock %}